package main.btlshyp.message;

public enum MessageType {
  CHAT,
  JOIN_ATTEMPT,
  JOIN_RESPONSE,
  GAME_START,
  SHIPS_PLACED,
  ATTACK_ATTEMPT,
  ATTACK_RESPONSE,
  TURN,
  GAME_WON_ATTEMPT,
  GAME_WON_RESPONSE,
  LOGIN,
}
